### PR TITLE
Lesson 9

### PR DESCRIPTION
**Pull request by mautoranzo**
I already started with my idea for the final project. Instead of doing jobs I will do something with a repertory of songs and chords for each user.

### CODE REVIEW

**Comment by aschey** [comment]
Hey @mautoranzo looks like this PR was accidentally opened against the main repo instead of your personal one.

**Comment by mautoranzo** [comment]
> Hey @mautoranzo looks like this PR was accidentally opened against the main repo instead of your personal one.

Yes sorry for that, here is the correct one https://github.com/mautoranzo/06-jobs-api/pull/1

**Comment by aschey** [comment]
You can close this PR then

**Comment by mautoranzo** [comment]
.

**Pull request closed without merging**
